import { PublicKey } from "@solana/web3.js"

export const dexes = [
  "Cropper",
  "Raydium",
  "Openbook",
  "StabbleWeightedSwap",
  "Guacswap",
  "OpenBookV2",
  "Aldrin",
  "MeteoraDLMM",
  "Saber(Decimals)",
  "SanctumInfinity",
  "Whirlpool",
  "StepN",
  "Dexlab",
  "RaydiumCP",
  "Mercurial",
  "LifinityV2",
  "ObricV2",
  "Meteora",
  "Phoenix",
  "TokenSwap",
  "HeliumNetwork",
  "Sanctum",
  "Moonshot",
  "StabbleStableSwap",
  "GooseFX",
  "Penguin",
  "AldrinV2",
  "OrcaV2",
  "LifinityV1",
  "1DEX",
  "CropperLegacy",
  "SolFi",
  "Oasis",
  "Saber",
  "Crema",
  "Pump.fun",
  "RaydiumCLMM",
  "Bonkswap",
  "Perps",
  "Fox",
  "Saros",
  "OrcaV1",
  "FluxBeam",
  "Invariant"]
  
  export const jitoAccounts = [
  new PublicKey("96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5"),
  new PublicKey("HFqU5x63VTqvQss8hp11i4wVV8bD44PvwucfZ2bU7gRe"),
  new PublicKey("Cw8CFyM9FkoMi7K7Crf6HNQqf4uEMzpKw6QNghXLvLkY"),
  new PublicKey("ADaUMid9yfUytqMBgopwjb2DTLSokTSzL1zt6iGPaS49"),
  new PublicKey("DfXygSm4jCyNCybVYYK6DwvWqjKee8pbDmJGcLWNDXjh"),
  new PublicKey("ADuUkR4vqLUMWXxW9gh6D6L8pMSawimctcNZ5pGwDcEt"),
  new PublicKey("DttWaMuVvTiduZRnguLF7jNxTgiMBZ1hyAumKUiL2KRL"),
  new PublicKey("3AVi9Tg9Uo68tJfuvoKvqKNWKkC5wPdSSdeBnizKZ6jT") ]
  
  export const jitoUrls = [
    "https://amsterdam.mainnet.block-engine.jito.wtf/api/v1/bundles",
    "https://frankfurt.mainnet.block-engine.jito.wtf/api/v1/bundles",
    "https://ny.mainnet.block-engine.jito.wtf/api/v1/bundles",
    "https://tokyo.mainnet.block-engine.jito.wtf/api/v1/bundles",
    "https://slc.mainnet.block-engine.jito.wtf/api/v1/bundles" ]
  